test:    #请务必保证 port host dir 输入的数量是一致的
  port: 8080      #用,(英文逗号分开)表示不同端口
  host: F盘上的tomcat #用,(英文逗号分开)表示不同服务器名字
  ip: 127.0.0.1    #暂时只为一个ip，个人觉得多个ip没有必要
  dir: E:/1.bat    #使用绝对路径，用,(英文逗号分开)表示不同端口的脚本，必须和host port的顺序一样,
  auto: 0 #如果不想要自动重启tomcat功能，请把is-auto-auto设置为0
mail:
  host:  #SMTP服务器地址
  username:  #登陆账号
  password:  #登陆密码（或授权码）
  from:  #邮件发信人（即真实邮箱）
  to_mail:   #要发送的邮箱的名字 用,（英文逗号）区分  可以同时发送多个邮箱
sms:
  #要发送的手机号码，多个号码如13800000000,13800000001,13800000002（用英文逗号区分开来）
  smsMob:
  #网建sms密钥
  Key:
  Uid:
server:
  port: 9787  # 服务启动的端口
